name = "vhagar/agent-escrow"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'vhagar/agent-escrow'"

[repository]
user = "vhagar"
project = "agent-escrow"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
